# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  config.vm.box = "ubuntu/focal64"
  config.vm.network "private_network", ip: "192.168.56.100"

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = "4"
    vb.memory = "8192"
  end

  config.vm.provision :ansible_local do |ansible|
    ansible.install_mode = "pip"
    ansible.galaxy_role_file = "provision/galaxy-requirements.yml"
    ansible.playbook = "provision/init.yml"
  end

  config.vm.provision :ansible_local, run: "always" do |ansible|
    ansible.install = false
    ansible.playbook = "provision/gtp5g.yml"
  end
end
