- name: install gtp5g prerequisite
  become: true
  ansible.builtin.apt:
    pkg:
      - build-essential

- name: clone gtp5g repo
  ansible.builtin.git:
    repo: "{{ gtp5g_repo_url }}"
    version: "{{ gtp5g_version }}"
    dest: "{{ gtp5g_clone_path }}"
    depth: 1

- name: cleanup gtp5g module build
  community.general.make:
    chdir: "{{ gtp5g_clone_path }}"
    target: clean

- name: build gtp5g module
  community.general.make:
    chdir: "{{ gtp5g_clone_path }}"

- name: install gtp5g module
  become: true
  community.general.make:
    chdir: "{{ gtp5g_clone_path }}"
    target: install

- name: enable QoS
  when: enable_qos
  ansible.builtin.command: echo 1 >  /proc/gtp5g/seq
